#!/bin/bash

branch=$(git symbolic-ref -q --short HEAD)

echo $branch
if [[ $branch =~ ^STAR-[0-9]+$ ]]; then
    ticket=$branch
elif [[ $branch =~ ^f/.* ]]; then
    ticket=$(echo $branch | sed -n 's/\f\/\([A-Z][A-Z]*-\d*\)/\1/p')
fi

if [ -n "$ticket" ]; then
    sed "1s/^/[$ticket] /" $1 > $1.new
    mv $1.new $1
fi
